### ISSUE TITLE
当前内核版本10558过低，管理器无法正常工作，请升级内核版本至10977或以上!

### ISSUE THREAD

**Issue by fivenoodle** [SlackerState/android_kernel_xiaomi_sm6150#1]
![Screenshot_2023-06-07-14-33-05-989_me weishu kernelsu](https://github.com/SlackerState/android_kernel_xiaomi_sm6150/assets/111843785/977c781a-fcd2-46d9-8333-a85374eb711a)
大佬帮忙看看

**Comment by SlackerState** [comment]
我已经很久没有跟进ksu的更新进行编译了，可以用action自己重新跑一下

**Comment by fivenoodle** [comment]
> 我已经很久没有跟进ksu的更新进行编译了，可以用action自己重新跑一下

大佬那你看看我这样填是不是对的![IMG_20230609_183439.jpg](https://github.com/SlackerState/android_kernel_xiaomi_sm6150/assets/111843785/a860ec85-71e3-4916-84c6-e0fe591199d7)

**Comment by fivenoodle** [comment]
(╥╯﹏╰╥)ง出现问题了，大佬你能看一下哪里出错了吗
![IMG_20230609_184222](https://github.com/SlackerState/android_kernel_xiaomi_sm6150/assets/111843785/e6b542dc-b88b-42cf-9559-3072fd58124e)

**Comment by SlackerState** [comment]
> (╥╯﹏╰╥)ง出现问题了，大佬你能看一下哪里出错了吗
> ![IMG_20230609_184222](https://github.com/SlackerState/android_kernel_xiaomi_sm6150/assets/111843785/e6b542dc-b88b-42cf-9559-3072fd58124e)
> 

你这个deconfig都没弄对，我这两天弄个action跑吧

**Comment by SlackerState** [comment]
action已经配置完成，请转至[Android-Kernel-Builder](https://github.com/SlackerState/Android-Kernel-Builder)仓库内的Acton下载最新编译的内容，其中包含了anykernel包和各个镜像，请注意其内核适用系统与本仓库内release注意事项一致。
